# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0010_restaurantlocation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='owner',
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
